### ISSUE TITLE
Always returns nil?

### ISSUE THREAD

**Issue by joegrist** [markbattistella/PhraseKit#34]
Confused why I only get `nil`.  Do the JSON word lists need to be linked into the build somehow? Sorry if this is a dumb question.

```swift
import SwiftUI
import PhraseKit

struct Random: View {

    var body: some View {

        let generator = PhraseGenerator()
        print(generator.generatePhrase(wordCount: .three)) // <---- "nil"
        ...
```

**Comment by markbattistella** [comment]
@joegrist - thanks for raising that! I've fixed it. When I was building in the word validator/profanity exclusion list, I updated the JSON modelling, but forgot to update the Bundle decoding for the new model.

Should all be working now, I tested it on my end :)

**Comment by joegrist** [comment]
Fabulous, verified, works great now.  Thanks!
